---
# Backups operate in "pull" mode from the backup-server.
# Therefore, we mostly need to configure the mysqldump on the client,
# but we also delegate to the backup-server the configuration of
# a rdiff-backup pull for backupninja.

- apt: update_cache=yes
  tags:
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - rdiff-backup
  tags:
    - packages

# - name: Backupninja | do not report success
#   replace: dest=/etc/backupninja.conf regexp='^reportsuccess = yes' replace='reportsuccess = no'

# Deploy backupninja rdiff config to onsite backup-server
- name: Backupninja | deploy rdiff hourly backup template
  template: src=etc/backup.d/90-hostname.rdiff dest="/etc/backup.d/{{ inventory_hostname }}.rdiff" mode=0600
  when: backupserver_hourly != "none"
  delegate_to: "{{ backupserver_hourly }}"
  tags:
    - backup-client
    - backup-client-configuration

- name: Backupninja | ensure that the backup directory exists
  file: path="/srv/backups/{{ inventory_hostname }}" state=directory owner=root group=root mode=0700
  when: backupserver_hourly != "none"
  delegate_to: "{{ backupserver_hourly }}"

# TODO: if no key exists, create one.

# Deploy root@backup-server ssh pubkey to client
- name: ssh | Get root ssh public key
  shell: cat /root/.ssh/id_rsa.pub
  when: backupserver_hourly != "none"
  delegate_to: "{{ backupserver_hourly }}"
  register: id_rsa_pub
  changed_when: false

- name: ssh | Add root client public key to authorized_keys
  authorized_key:
    user="root"
    key="{{ id_rsa_pub.stdout }}"
    key_options='no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty,from="140.211.166.28"'
  when: backupserver_hourly != "none"

# Add client host key to known_hosts of backup server (which does pull)
- name: ssh | Run ssh-keyscan to get client fingerprint
  shell: "ssh-keyscan -H -T 10 {{ inventory_hostname }}"
  register: host_fingerprint
  when: backupserver_hourly != "none"
  changed_when: false
  delegate_to: "{{ backupserver_hourly }}"

- name: ssh | Add client ssh host key fingerprint to known_hosts of server to avoid prompt
  known_hosts:
    name="{{ inventory_hostname }}"
    key="{{ host_fingerprint.stdout }}"
  when: backupserver_hourly != "none"
  delegate_to: "{{ backupserver_hourly }}"
