---
# Override in /etc/ansible/group_vars/all
# or per-host in /etc/ansible/host_vars/[host]
aegir_sudoers: johndoe

# Permissions on /var/aegir/.ssh
# Some types of hacks (ex: WordPress plugin upgrades) override this to 0750/www-data
aegir_ssh_dir_permission: 0700
aegir_ssh_dir_group: aegir
