---

# Update the buildkit installation
# Note: The file layout here is a bit older. At time of writing, suspect it only applies ot `www-demo`. Haven't really tried this playbook in a long time.
# To use it: $ ansible-playbook ./playbooks/buildkit_update.yml

## TLDR: su jenkins; cd /srv/buildkit && git pull && ./civi-download-tools

- hosts: test-servers
  tasks:
    - name: Update buildkit git repo
      git: repo=https://github.com/civicrm/civicrm-buildkit dest=/srv/buildkit version=master
      become: yes
      become_user: jenkins

    - name: Run civi-download-tools
      shell: ./civi-download-tools
      args:
        chdir: /srv/buildkit/bin
      become: yes
      become_user: jenkins
