---
- apt: pkg=postfix state=installed
- apt: pkg=opendkim state=installed
- apt: pkg=opendkim-tools state=installed

# CiviCRM key
# Not all servers can use this, and we don't receive email anyway.
# - name: Test if the civicrm.org key is present.
#   stat: path=/etc/ssl/private/wildcard.civicrm.org.key
#   register: stkey
# 
# - set_fact:
#     postfix_key: "/etc/ssl/private/wildcard.civicrm.org.key"
#     when: stkey.stat.exists
# 
# - name: Test if the civicrm.org cert bundle is present.
#   stat: path=/etc/ssl/private/wildcard.civicrm.org.bundled.crt
#   register: stcrt
# 
# - set_fact:
#     postfix_cert: "/etc/ssl/private/wildcard.civicrm.org.bundled.crt"
#     when: stcrt.stat.exists

- name: Set the postfix mailname (and chmod it to be public, required by Aegir).
  template:
    src: "etc/mailname"
    dest: "/etc/mailname"
    owner: "root"
    group: "root"
    mode: 0644

- name: Deploy the postfix main.cf configuration.
  template:
    src: "etc/postfix/main.cf"
    dest: "/etc/postfix/main.cf"
    owner: "root"
    group: "root"
    mode: 0644

# TODO
# - name: Deploy the opendkim default configuration.
#   template:
#     src: "etc/default/opendkim"
#     dest: "/etc/default/opendkim"
#     owner: "root"
#     group: "root"
#     mode: 0644
# 
# - name: Deploy the opendkim main configuration.
#   template:
#     src: "etc/opendkim.conf"
#     dest: "/etc/opendkim.conf"
#     owner: "root"
#     group: "root"
#     mode: 0644

- name: Ensure that the postfix run directory exists.
  file: path=/var/spool/postfix/run/ state=directory owner=postfix

- name: Ensure that the opendkim socket directory exists.
  file: path=/var/spool/postfix/run/opendkim/ state=directory owner=opendkim

- name: Ensure that the opendkim keys directory exists and is restricted.
  file: path=/etc/opendkim/ state=directory owner=opendkim group=opendkim mode=0700

# - name: Deploy the public OpenDKIM key
#   copy: src=/etc/ansible/files/etc/opendkim/201409.txt dest=/etc/opendkim/201409.txt owner=opendkim group=opendkim mode=0600
# 
# - name: Deploy the private OpenDKIM key
#   copy: src=/etc/ansible/files/etc/opendkim/201409.private dest=/etc/opendkim/201409.private owner=opendkim group=opendkim mode=0600
# 
# - stat: path=/etc/opendkim/201409.private
#   register: stkey
# 
# - name: Set OpenDKIM private key permissions.
#   file: path=/etc/opendkim/201409.private owner=opendkim group=opendkim mode=0600
#   when: (stkey.stat.exists == true)
# 
# - name: Set OpenDKIM public key permissions.
#   file: path=/etc/opendkim/201409.txt owner=opendkim group=opendkim mode=0600
#   when: (stkey.stat.exists == true)
 
- name: Add postfix in the opendkim group.
  user: name=postfix groups=opendkim append=yes

# fixme: use notify
- name: Restart postfix because of the ipv4 protocol change (unbind ipv6).
  service: name=postfix state=restarted

# - name: Restart opendkim.
#   service: name=opendkim state=restarted
