---

- apt: pkg=apt-transport-https state=installed
  tags:
    - packages
    - filebeat

- apt_key:
    url=https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state=present
    validate_certs=false # on stretch, running into weird invalid cert error?
  tags:
    - packages
    - filebeat

- apt_repository:
    repo='deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state=present
    update_cache=yes
  tags:
    - packages
    - filebeat

- name: Delete the old Filebeat repository
  file: path="/etc/apt/sources.list.d/packages_elastic_co_beats_apt.list" state=absent
  tags:
    - packages
    - filebeat

# This is weird, but the version check otherwise fails if filebeat
# is not installed.
- apt: pkg=filebeat state=installed install_recommends=no
  tags:
    - packages
    - filebeat

- name: Get the current filebeat version
  shell: "dpkg -s filebeat | grep '^Version' | awk '{print $2}'"
  register: filebeat_version
  tags:
    - packages
    - filebeat

- name: Remove the old Filebeat package
  apt: pkg=filebeat state=absent
  when: filebeat_version.stdout | version_compare('6.1', '<')
  tags:
    - packages
    - filebeat

- name: Delete the old Filebeat registry
  file: path="/var/lib/filebeat/registry" state=absent
  when: filebeat_version.stdout | version_compare('6.1', '<')
  notify: restart filebeat
  tags:
    - packages
    - filebeat

- apt: pkg=filebeat state=installed install_recommends=no
  tags:
    - packages
    - filebeat

- service: name=filebeat state=started enabled=yes

- name: Deploy the filebeat configuration.
  template:
    src: "filebeat.yml"
    dest: "/etc/filebeat/filebeat.yml"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart filebeat
  tags:
    - filebeat
