#!/bin/bash

# {{ ansible_managed }}

# Outputs the contents of the Aegir usage.log in a way that Icinga2
# can fetch the metrics so that they can be fed to Graphite/Grafana.
# It does not do any quota checks at the moment.

# Ex input: 
# aegir,example.org,DirSize:609816

# Expected output:
# AEGIR DISK OK - [comment] | 'label'=value[UOM];[warn];[crit];[min];[max]
# .. where UOM: (unit of measurement) is: s, %, B / KB / MB / TB, c (counter)

# Extract the production sites (grep -v skip)
# .. keep only DirSize entries
# and remove the 'aegir,' prefix (cut ..)
sites=$(cat /var/log/aegir/usage.log | grep -v ',skip$' | grep DirSize | cut -f 2- -d ',')

echo -n "AEGIR DISK OK |"

while read -r line; do

  # Match the first field
  site_name=${line%%,*}
  site_name=${site_name//./_}

  # Match the last field
  site_size=${line##*:}

  echo -n " $site_name=${site_size}KB;"
done <<< "$sites"
