#!/usr/bin/php
<?php

$host = trim($argv[1]);
$cms = trim($argv[2]);

if (empty($host)) {
  echo 'Missing host argument.';
  exit(3);
}

$tmp = '';
$civistatus = '';

if ($cms == 'drupal' || $cms == 'drupal8') {
  exec('sudo -u aegir /usr/local/bin/drush @' . escapeshellarg($host) . ' cvapi System.check --out=json', $tmp);
}
elseif ($cms == 'wordpress') {
  exec('sudo -u aegir /usr/local/bin/drush @' . escapeshellarg($host) . ' wp cv api System.check --out=json --strict=0', $tmp);
}
elseif ($cms == 'joomla') {
  global $civicrm_cli;
  global $civicrm_cli_ini; // required if TZ is not the same as the server
  global $civicrm_cron_user;
  global $civicrm_cron_pass;

  require_once '/etc/civicrm/' . $host . '.php';

  if ($civicrm_cli_ini) {
    exec('sudo -u www-data /usr/bin/env php -c ' . escapeshellarg($civicrm_cli_ini) . ' ' . escapeshellarg($civicrm_cli) . ' -s ' . escapeshellarg($host) . ' -u ' . escapeshellarg($civicrm_cron_user) . ' -p ' . escapeshellarg($civicrm_cron_pass) . ' -e System -a check --json', $tmp);
  }
  else {
    exec('sudo -u www-data /usr/bin/env php ' . escapeshellarg($civicrm_cli) . ' -s ' . escapeshellarg($host) . ' -u ' . escapeshellarg($civicrm_cron_user) . ' -p ' . escapeshellarg($civicrm_cron_pass) . ' -e System -a check --json', $tmp);
  }
}
else {
  echo 'Unsupported CMS: ' . $cms;
  exit(3);
}

if ($tmp) {
  if ($cms == 'joomla') {
    $civistatus = json_decode(implode(' ', $tmp));
  }
  else {
    $civistatus = json_decode($tmp[0]);
  }

  $check_status = 0;
  $check_descriptions = array();

  if (empty($civistatus)) {
    if ($cms == 'drupal' || $cms == 'drupal8') {
      exec('sudo -u aegir /usr/local/bin/drush @' . escapeshellarg($host) . ' cc drush');
      echo 'Failed to check status (1). Drush cache flushed for the next run.';
    }
    else {
      echo 'Failed to check status (1).';
    }

    exit(3);
  }

  if ($civistatus->is_error) {
    echo 'API call failed: ' . $civistatus->error_message;
    exit(3);
  }

  foreach ($civistatus->values as $key => $val) {
    // Issue was acknowledged (hidden from the Status Check UI).
    if (!$val->is_visible) {
      continue;
    }

    if (in_array($val->severity, ['warning', 'error', 'critical'])) {
      // We don't want to downgrade an 'error' status to 'warning'.
      if ($check_status == 0) {
        $check_status = 1;
      }

      $check_descriptions[] = $val->title;
    }

    if ($val->severity == 'error' || $val->severity == 'critical') {
      $check_status = 2;
    }
  }

  if ($check_status == 0) {
    echo 'OK';
    exit(0);
  }
  else {
    echo implode(' ', $check_descriptions);
    exit($check_status);
  }
}

if ($cms == 'drupal' || $cms == 'drupal8') {
  exec('sudo -u aegir /usr/local/bin/drush @' . escapeshellarg($host) . ' cc drush');
}

echo 'Failed to check status (2). Drush cache flushed for the next run.';
exit(3);
