#!/bin/bash

#################################################################
# Creation: Edouard Lamoine
# Last Modification:6 mai 2015
# This script is verifying if UFW is active or not
# Based on: https://exchange.nagios.org/directory/Plugins/Security/check_ufw-(edouard-2Elamoine)/details
#################################################################

STATE=$(env LANGUAGE=C ufw status)

if [[ ! $STATE =~ "active" ]]; then
  echo "UNKNOWN - Impossible to determine UFW status"
  exit 3
fi

if [[ $STATE =~ "inactive" ]]; then
  echo "CRITICAL - UFW is inactive"
  exit 2
fi

if [[ $STATE =~ "active" ]]; then
  echo "OK - UFW is active"
  exit 0
fi
