#!/bin/bash

# {{ ansible_managed }}

while getopts "s:t:a:S:" opt; do
  case $opt in
    s)
      servicestate=$OPTARG
      ;;
    t)
      servicestatetype=$OPTARG
      ;;
    a)
      serviceattempt=$OPTARG
      ;;
    S)
      service=$OPTARG
      ;;
  esac
done
echo "COUCOU $service" >> /tmp/test.log

if ( [ -z $servicestate ] || [ -z $servicestatetype ] || [ -z $serviceattempt ] || [ -z $service ] ); then
  echo "USAGE: $0 -s servicestate -t servicestatetype -a serviceattempt -S service"
  exit 3;
fi

# https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#event-commands
# servicestate = { CRITICAL, WARNING, UNKNOWN, OK }
# servicestatetype = { SOFT, HARD }, i.e. old or recent state change.
# serviceattempt = number of attempts of the event type

# Only restart on the third attempt of a critical event
if ( [ $servicestate == "CRITICAL" ] || [ $servicestate == "WARNING" ] ); then
  sudo systemctl restart $service
fi
