---
# Adjust this to your infra!
logstash_forwarder_server: localhost
logstash_forwarder_server_port: 5000
logstash_ssl_ca_cert: /etc/ssl/path/to/ca-certificate.crt

logstash_forwarder_files:
  - paths:
      - /var/log/messages
      - /var/log/auth.log
    fields:
      type: syslog
  # To add more sets of files...
  # - paths:
  #     - /var/log/boot.log
  #   fields:
  #     type: syslog
