---

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - sudo
  tags:
    - packages

- name: User | create user
  command: "useradd -m {{ deploy_user }} -G sudo creates=/home/{{ deploy_user }}"

- name: User | authorized key upload
  authorized_key:
    user="{{ deploy_user }}"
    key="{{ lookup('file', '/etc/ansible/files/civicrm/sshkeys/{{ deploy_user }}.pub') }}"

- name: Sudoers | create deploy sudoers file
  template: src=sudoers.j2 dest=/etc/sudoers.d/ansible owner=root group=root mode=0440
