---

# These packages have been used with 12.04+buildkit:
# See also: do_system_precise
# https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L307

# Currently we are using rip84's PPA for Ubuntu Precisel:
# http://ppa.launchpad.net/rip84/php/

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xD4B504A8EE379B61"
    state=present

- apt_repository:
    repo='deb http://ppa.launchpad.net/rip84/php5/ubuntu precise main '
    state=present
    update_cache=yes
