---

# We deploy our sources.list to include "contrib"
- name: common-all | Deploy apt sources.list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  tags:
    - common-all

- apt: update_cache=yes
  tags:
    - packages
    - common-all

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - etckeeper
    - fail2ban
    - gawk
    - git
    - less
    - libpam-yubico
    - ncdu
    - ntpdate
    - tmux
    - ufw
    - unattended-upgrades
    - unzip
    - vim
    - vnstat
    - wget
    - whois
    - zip
  tags:
    - packages
    - common-all

- name: network | Deploy IPv6 configuration script
  template: src=etc/network/if-up.d/civicrm-ipv6 dest=/etc/network/if-up.d/civicrm-ipv6 owner=root group=root mode=0755
  when: preseed_ipv6_address is defined
  tags:
    - common-all
    - common-all-ipv6
