---
# Install basic things which must be everywhere.
- apt: update_cache=yes
  tags:
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - etckeeper
    - fail2ban
    - vnstat
    - git
    - libpam-yubico
    - ncdu
    - ntpdate
    - tmux
    - ufw
    - unzip
    - vim
  tags:
    - packages

# Configure the firewall
- name: Allow ssh
  ufw: proto=tcp port=22 rule=allow

- name: Allow http
  ufw: proto=tcp port=80 rule=allow

- name: Allow https
  ufw: proto=tcp port=443 rule=allow

- name: Allow access to munin-node from munin servers
  ufw: proto=tcp port=4949 rule=allow src={{ item }}
  with_items: ufw_munin_allow_src

- name: Allow access to NRPE from nagios servers
  ufw: proto=tcp port=5666 rule=allow src={{ item }}
  with_items: ufw_nrpe_allow_src

# see https://github.com/ansible/ansible/issues/10047 for why the weird default.
- ufw: proto={{ item.value.proto }} port={{ item.value.port }} src={{ item.value.src }} rule={{ item.value.rule }}
  with_dict: ufw_extra | default({})

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny

- name: Restart ufw
  service: name=ufw state=restarted
