---

# We deploy our sources.list to include "contrib"
- name: common-all | Deploy apt sources.list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  tags:
    - common-all

- apt: update_cache=yes
  tags:
    - packages
    - common-all

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - etckeeper
    - fail2ban
    - gawk
    - git
    - less
    - libpam-yubico
    - ncdu
    - ntpdate
    - tmux
    - ufw
    - unattended-upgrades
    - unzip
    - vim
    - vnstat
    - wget
    - whois
    - zip
  tags:
    - packages
    - common-all

# Configure the firewall
- name: Allow ssh
  ufw: proto=tcp port=22 rule=allow
  tags:
    - ufw

- name: Allow http
  ufw: proto=tcp port=80 rule=allow
  tags:
    - ufw

- name: Allow https
  ufw: proto=tcp port=443 rule=allow
  tags:
    - ufw

- name: Allow access to munin-node from munin servers
  ufw: proto=tcp port=4949 rule=allow src={{ item }}
  with_items: "{{ ufw_munin_allow_src }}"
  tags:
    - ufw

- name: Allow access to NRPE from nagios servers
  ufw: proto=tcp port=5666 rule=allow src={{ item }}
  with_items: "{{ ufw_nrpe_allow_src }}"
  tags:
    - ufw

- name: Allow access to icinga2 satellite daemon from main servers
  ufw: proto=tcp port=5665 rule=allow src={{ item }}
  with_items: "{{ ufw_icinga2_allow_src }}"
  tags:
    - ufw

# see https://github.com/ansible/ansible/issues/10047 for why the weird default.
- ufw: proto={{ item.value.proto }} port={{ item.value.port }} src={{ item.value.src }} rule={{ item.value.rule }}
  with_dict: "{{ ufw_extra | default({}) }}"
  tags:
    - ufw

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny
  tags:
    - ufw

- name: Restart ufw
  service: name=ufw state=restarted

- name: network | Deploy IPv6 configuration script
  template: src=etc/network/if-up.d/civicrm-ipv6 dest=/etc/network/if-up.d/civicrm-ipv6 owner=root group=root mode=0755
  when: preseed_ipv6_address is defined
  tags:
    - common-all
    - common-all-ipv6
