---
# Only install basic things which must be everywhere.
- apt: pkg=etckeeper state=installed update_cache=yes
- apt: pkg=fail2ban state=installed
- apt: pkg=vnstat state=installed
- apt: pkg=git state=installed
- apt: pkg=libpam-yubico state=installed
- apt: pkg=ncdu state=installed
- apt: pkg=ntpdate state=installed
- apt: pkg=tmux state=installed
- apt: pkg=unzip state=installed
- apt: pkg=vim state=installed

# Firewall (iptables)
- name: Install ufw
  apt: name=ufw

- name: Allow ssh
  ufw: proto=tcp port=22 rule=allow

- name: Allow http
  ufw: proto=tcp port=80 rule=allow

- name: Allow https
  ufw: proto=tcp port=443 rule=allow

- name: Allow access to munin-node from munin servers
  ufw: proto=tcp port=4949 rule=allow src={{ item }}
  with_items: ufw_munin_allow_src

- name: Allow access to NRPE from nagios servers
  ufw: proto=tcp port=5666 rule=allow src={{ item }}
  with_items: ufw_nrpe_allow_src

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny

- name: Restart ufw
  service: name=ufw state=restarted
