---
# Backups operate in "pull" mode from the backup-server,
# but most of the configuration is done by the backup-client role.
# We just need to make sure that the backup-server has the basics.

- apt: update_cache=yes
  tags:
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - backupninja
    - rdiff-backup
  tags:
    - packages

- name: Backupninja | do not report success
  replace: dest=/etc/backupninja.conf regexp='^reportsuccess = yes' replace='reportsuccess = no'

- name: Generating ssh RSA key for root
  user: name=root generate_ssh_key=yes
