---

# Stretch does not have npm
- name: Get the nodejs repo key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  tags:
    - nodejs
    - packages

- apt_repository:
    repo='deb https://deb.nodesource.com/node_8.x stretch main'
    state=present
    update_cache=yes
  when: ansible_distribution_release == "stretch"
  tags:
    - nodejs
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - nodejs
  when: ansible_distribution_release == "stretch"
  tags:
    - nodejs
    - packages

# libssl-dev from jessie-backports required for nodejs-dev, for node-gyp, for node, for npm..
- apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
    default_release: jessie-backports
  with_items:
    - libssl-dev
    - npm
  when: ansible_distribution_release == "jessie"
  tags:
    - packages
