---
- hosts: servers
  sudo: yes
  roles:
    - common-all
    - backup-client
    - filebeat
    - mysqlbackup
    - ufw
    - unattended-upgrades
    - sshuserkeys
  tags:
    - minimum

- hosts: icinga-satellite
  sudo: yes
  roles:
    - icinga2
  tags:
    - icinga
    - icinga2

- hosts: all
  sudo: yes
  roles:
    - backup-client
  tags:
    - backup-client

- hosts: backup-servers
  sudo: yes
  roles:
    - backup-server
  tags:
    - backup-server

- hosts: kvm-servers
  sudo: yes
  roles:
    - common-all
    - kvm-server
  tags:
    - kvm-server

- hosts: mattermost-servers
  sudo: yes
  roles:
    - mattermost
  tags:
    - mattermost

- hosts: test-servers
  sudo: yes
  roles:
    - test-node
  tags:
    - test-node

- hosts: demo-servers
  sudo: yes
  roles:
    - demo
    - nodejs
  tags:
    - demo

- hosts: php71-servers
  sudo: yes
  roles:
    - php71
  tags:
    - php71

- hosts: php7-servers
  sudo: yes
  roles:
    - php7
  tags:
    - php7

- hosts: php56-servers
  sudo: yes
  roles:
    - php56
  tags:
    - php56

- hosts: php55-servers
  sudo: yes
  roles:
    - php55
  tags:
    - php55

- hosts: php54-servers
  sudo: yes
  roles:
    - php54
  tags:
    - php54

- hosts: buildkit-servers
  sudo: yes
  roles:
    - buildkit
  tags:
    - buildkit

- hosts: mkdocs-servers
  sudo: yes
  roles:
    - mkdocs
  tags:
    - mkdocs

- hosts: jira-servers
  sudo: yes
  roles:
    - jira
  tags:
    - jira

- hosts: gitlab-servers
  sudo: yes
  roles:
    - gitlab
  tags:
    - gitlab

- hosts: stats-servers
  sudo: yes
  roles:
    - civicrm-stats
  tags:
    - civicrm-stats

- hosts: ldap-servers
  sudo: yes
  roles:
    - ldap-auth-server
  tags:
    - ldap-auth-server

- hosts: ldapcivi-servers
  sudo: yes
  roles:
    - ldapcivi
    - dehydrated
  tags:
    - ldapcivi

- hosts: gitbot-servers
  sudo: yes
  roles:
    - nodejs
  tags:
    - gitbot-servers

- hosts: aegir-managed
  become: yes
  become_user: root
  roles:
    - aegir
    - gitlab-runner
  tags:
    - aegir

# NB: Aegir handles LE/dehydrated already.
- hosts: dehydrated-manually
  become: yes
  become_user: root
  roles:
    - dehydrated
  tags:
    - dehydrated
