---
- hosts: servers
  sudo: yes
  roles:
    - common-all
    - sslcerts
    - logstash-forwarder
    - backup-client

- hosts: ldap-managed
  sudo: yes
  roles:
    - ldap-auth-client

- hosts: logstash-servers
  sudo: yes
  roles:
    - logstash
