---

# These packages have been used with Xenial+buildkit:
# See also: do_system_xenial
# https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L307

# Makes it easier to eventually switch between different versions (ex: 5.6).
# TODO: cleanup so that we have only one PHP role for all versions.

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C"
    state=present
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "16")
  tags: php71

- apt_repository:
    repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main'
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "16")
  tags: php71

- name: Debian | Add Sury.org apt reporitory key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/php.gpg
  when: ansible_distribution == "Debian"
  tags:
    - php71

- apt_repository:
    repo="deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state=present
    update_cache=yes
  when: (ansible_distribution == "Debian")
  tags: php71

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-fpm
    - php7.1-gd
    - php7.1-imap
    - php7.1-intl
    - php7.1-json
    - php7.1-ldap
    - php7.1-mbstring
    - php7.1-mcrypt
    - php7.1-mysql
    - php7.1-opcache
    - php7.1-readline
    - php7.1-recode
    - php7.1-soap
    - php7.1-sqlite3
    - php7.1-xml
    - php7.1-xmlrpc
    - php7.1-xsl
    - php7.1-zip
    - php7.1-bcmath
    - apache2
    - libapache2-mod-php7.1
  tags: php71
