#!/bin/bash

# {{ ansible_managed }}

sysctl -w net.ipv6.conf.all.autoconf=0
sysctl -w net.ipv6.conf.all.accept_ra=0

ip -6 route del default

ip -6 addr add {{ preseed_ipv6_address }} dev {{ preseed_ipv6_dev }}
ip -6 route add {{ preseed_ipv6_route }} dev {{ preseed_ipv6_dev }}
ip -6 route add default via {{ preseed_ipv6_gateway }} dev {{ preseed_ipv6_dev }}
