---
- name: reload apache2
  become: yes
  service:
    name: apache2
    state: reloaded
    enabled: yes

- name: restart apache2
  become: yes
  service:
    name: apache2
    state: restarted
    enabled: yes
